config/routes.rb
Rails.application.routes.draw do
  root 'homes#index'
  resources :sensors do
    resources :sensor_logs
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/sensor.rb
class Sensor < ApplicationRecord
  extend Enumerize

  enumerize :program_language, in: [:ruby, :python, :"node-red", :etc]
  has_many :sensor_logs, dependent: :destroy
end

app/models/sensor_log.rb
class SensorLog < ApplicationRecord
  belongs_to :sensor
end

app/models/system_setting.rb
class SystemSetting < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def index
  end
end

app/controllers/sensors_controller.rb
class SensorsController < ApplicationController
  def index
    @search = Sensor.ransack(params[:q])
    @sensors = @search.result
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/sensors_helper.rb
module SensorsHelper
end

app/views/application/_footer.html.slim
.content.has-text-centered
  p
    strong Licensed by 

app/views/application/_header.html.slim
nav.navbar aria-label=("main navigation") role="navigation" 
  .navbar-brand
    a.navbar-item href="./"
      img alt=("トップ") height="28"  width="112" /
    a.navbar-burger aria-expanded="false" aria-label="menu" role="button" 
      span aria-hidden="true" 
      span aria-hidden="true" 
      span aria-hidden="true"
    .navbar-menu
      = link_to "センサー", sensors_path, class:"navbar-item"

app/views/homes/index.html.slim
section.hero.is-primary
  .hero-body
    .container
      h1.title
        | IoT活用研究会
      h2.subtitle
        | ラズパイセンサー計測

app/views/layouts/application.html.slim
doctype html
html
  head
    meta content=("text/html; charset=UTF-8") http-equiv="Content-Type" /
    title RaspberryClient
    = csrf_meta_tags
    = csp_meta_tag
    meta content="width=device-width,initial-scale=1" name="viewport" /
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = stylesheet_pack_tag 'application'
    = javascript_pack_tag 'application'
  body
    header
      = render 'header'
    = yield
    footer.footer
      = render 'footer'

app/views/sensors/_search.html.slim
= search_form_for @search do |f|
  .field.has-addons
    .control
      = f.search_field :name_cont, class: "input", placeholder: 'センサー名'
    .control
      = f.submit "検索", class: "button is-link"

app/views/sensors/_sensor.html.slim
td = sensor.id
td = sensor.name
td = sensor.sampling_cycle
td = link_to "ログ", sensor_sensor_logs_path(sensor), { class: "button" }
td = link_to "編集", sensor_path(sensor), { class: "button" }
td = link_to "削除", sensor_path(sensor), { class: "button" }

app/views/sensors/index.html.slim
section.hero.is-primary
  .hero-body
    .container
      h1.title
        | センサーの一覧

section.section
  .container
    .columns
      .column
        = render "search"
      .column
        = link_to "センサー追加", new_sensor_path, class: "button"

section.section
  .container
    table.table
      thead
        th ID
        th センサー名
        th センサータイプ
        th センサーログ
        th
        th
      tbody
        = render @sensors